---
gimmeVersion: v1
gimme:
  alias: example
  init: |
    git co main && git pull
  env:
    TEST_TOKEN: abcd1234hjkl
  kube: "~/.kube/kubeconfig-example.yaml" # Requires kubeconfigNonsense: true in root config