name: Build Gimme-Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-build:
    name: "Go Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.1
      - name: Install Dependencies
        working-directory: gimme-core
        run: |
          go get .
      - name: Build
        working-directory: gimme-core
        run: go build -v ./...
      - name: Test
        working-directory: gimme-core
        run: go test -v ./...